services:
  #name of the app (in this case vue-app)
  vue-app:
    build:
      context: ./
      dockerfile: ./dockerfiles/dev.dockerfile
    
    ports:
      - "8000:8000"
    #a volume in the host to install the project
    volumes:
      - ./vue:/app