services:
  #name of the app (in this case vue-app)
  vue-app:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    
    ports:
      - "8000:8000"
    #a volume in the host to install the project and map host node_modules to container
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

